
sampling_rules =  {
  "version": 2,
  "rules": [
    {
      "description": "DEBUG",
      "host": "*",
      "http_method": "*",
      "url_path": "/*",
      "fixed_target": 1,
      "reservoir": 200,
      "rate": 1
    }
  ],
  "default": {
    "fixed_target": 1,
    "reservoir": 20,
    "rate": 1
  }
}

Rails.application.config.xray = {
    # default segment name generated by XRay middleware
    name: 'imagetrends',
    sampling: true,
    sampling_rules: sampling_rules,
    patch: %I[net_http aws_sdk],
    # record db transactions as subsegments
    active_record: true,
    context_missing: 'LOG_ERROR'
  }
