Description: >
    This template deploys an RDS instance to the provided VPC and subnets.

Parameters:

    DBInstanceType:
        Description: An environment name that will be prefixed to resource names
        Type: String
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    VPC:
        Description: Choose which VPC this ECS cluster should be deployed to
        Type: AWS::EC2::VPC::Id
    Subnets:
        Description: Choose which subnets this RDS instance should be deployed to
        Type: List<AWS::EC2::Subnet::Id>
    SecurityGroup:
        Description: Select the Security Group to use for the RDS Instance
        Type: AWS::EC2::SecurityGroup::Id
    DBName:
        Description: Database Name
        Type: String
    DBUser:
        Description: Database User Name
        Type: String
    DBPassword:
        Description: Database Password
        Type: String

Resources:

    DatabaseSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: CloudFormation managed DB subnet group.
        SubnetIds: !Ref "Subnets"

    DatabaseCluster:
      Type: AWS::RDS::DBCluster
      Properties:
        Engine: aurora
        MasterUsername: !Ref "DBUser"
        MasterUserPassword: !Ref "DBPassword"
        DBSubnetGroupName: !Ref "DatabaseSubnetGroup"
        VpcSecurityGroupIds: [!Ref "SecurityGroup"]

    DatabasePrimaryInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: aurora
        DBClusterIdentifier: !Ref "DatabaseCluster"
        DBInstanceClass: !Ref DBInstanceType

Outputs:

    PrimaryInstanceName:
        Description: A reference to RDS Primary Instance Name
        Value: !GetAtt DatabasePrimaryInstance.Endpoint.Address

    PrimaryInstancePort:
        Description: A reference to RDS Primary Instance Port
        Value: !GetAtt DatabasePrimaryInstance.Endpoint.Port